using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using PeachPDF.SourceGenerators.Model;

namespace PeachPDF.SourceGenerators.Emit
{
    /// <summary>
    /// Emits <c>ComputedStyleAreas.g.cs</c> (namespace <c>PeachPDF.Html.Core.Dom</c>) — one
    /// <c>partial record</c> per <c>html.area</c> value appearing in <c>css-properties.json</c>, each
    /// holding one <c>{ get; init; }</c> field per property whose <c>html.area</c> names it. The
    /// hand-written <c>ComputedStyleAreas.cs</c> keeps <c>ComputedStyleCow</c> (shared copy-on-write
    /// infra, not per-property) and the handful of fields with no JSON entry at all (e.g.
    /// <c>FontArea.FontFamilyList</c>), each declared on a matching <c>partial record</c>.
    /// </summary>
    internal static class AreasEmitter
    {
        public static string Emit(IReadOnlyList<PropertyEntry> entries)
        {
            var areaEntries = entries
                .Where(e => e.Html is { Area: not null, PropertyPath: not null })
                .ToList();

            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generated by PeachPDF.SourceGenerators from css-properties.json. Do not edit by hand —");
            sb.AppendLine("// edit the JSON entry and rebuild. See CLAUDE.md's generator section.");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using PeachPDF.CSS;");
            sb.AppendLine("using PeachPDF.Html.Core.Entities;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("namespace PeachPDF.Html.Core.Dom");
            sb.AppendLine("{");

            var seenAreas = new HashSet<string>();
            foreach (var entry in areaEntries)
            {
                var area = entry.Html!.Area!;
                if (!seenAreas.Add(area)) continue;

                // A legacy alias (page-break-after → break-after) declares the same html.area/propertyPath
                // as the property it aliases, so it shares that area field rather than getting its own -
                // deduplicate by propertyPath within the area, keeping the first entry's declaration.
                var fields = areaEntries
                    .Where(e => e.Html!.Area == area)
                    .GroupBy(e => e.Html!.PropertyPath)
                    .Select(g => g.First())
                    .ToList();
                EmitArea(sb, area, fields);
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void EmitArea(StringBuilder sb, string area, List<PropertyEntry> entries)
        {
            sb.AppendLine($"    internal sealed partial record {area}");
            sb.AppendLine("    {");
            sb.AppendLine($"        internal static readonly {area} Default = new();");

            foreach (var entry in entries)
            {
                var html = entry.Html!;
                var defaultExpr = BuildDefaultExpression(entry);
                sb.Append($"        public {html.CsharpDataType} {html.PropertyPath} {{ get; init; }}");
                sb.AppendLine(defaultExpr is null ? "" : $" = {defaultExpr};");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        /// <summary>
        /// The area field's static default-value expression, or null to leave it as the type's own
        /// implicit default (every field with no JSON entry, or whose <c>csharpDataType</c> the generator
        /// doesn't know how to construct from <see cref="CssDefaults.GetInitialValue"/>'s plain string —
        /// e.g. <c>CssImage?</c>/<c>IReadOnlyList&lt;CssImage&gt;?</c> fields populated only via a
        /// <c>customSetter</c>, matching the hand-written convention for those fields today).
        /// </summary>
        private static string? BuildDefaultExpression(PropertyEntry entry)
        {
            var html = entry.Html!;
            // A CSS name's PascalCase doesn't reliably match its PropertyNames field's identifier (e.g.
            // "unicode-bidi" -> PropertyNames.UnicodeBidirectional, "page" -> PropertyNames.PageName) -
            // CssDefaults.GetInitialValue takes the plain CSS name string directly, so pass entry.Name as
            // a literal instead of trying to rederive the field's identifier.
            var initialValueExpr = $"CssDefaults.GetInitialValue({Identifier.StringLiteral(entry.Name)})!";

            if (entry.CssDataTypes.Count == 1 && entry.CssDataTypes[0].Kind == DataTypeKind.EnumKeyword)
            {
                var dt = entry.CssDataTypes[0];
                return $"CssProperty<global::PeachPDF.CSS.{dt.EnumType}>.FromCssText({initialValueExpr}, {dt.KeywordMap}, global::PeachPDF.CSS.{dt.Fallback})";
            }

            if (entry.CssDataTypes.Count == 1 && entry.CssDataTypes[0].Kind == DataTypeKind.KeywordOrValue)
            {
                var dt = entry.CssDataTypes[0];
                var resolved = KeywordOrValueGrammar.Resolve(entry, dt);
                return $"global::PeachPDF.CSS.CssKeywordOrValueParser.FromCssText<global::PeachPDF.CSS.{dt.EnumType}, {resolved.CSharpType}>" +
                       $"({initialValueExpr}, {dt.KeywordMap}, {resolved.TryParseMethod}, global::PeachPDF.CSS.{dt.Fallback})";
            }

            if (html.CsharpDataType == "string") return initialValueExpr;

            // A CssProperty<T> not covered by the enum-keyword/keyword-or-value branches above (e.g.
            // grid-template-columns/-rows, whose cssDataType is "cssom" - grammar validation and real
            // parsing are delegated to the CSS-OM/customSetter, not a generator-known FromCssText path).
            // Its initial keyword ("none") has no corresponding parsed T, so - matching the hand-written
            // precedent this mirrors - the parsed half stays a literal null; only the raw text is set.
            if (html.CsharpDataType is { } csharpType &&
                csharpType.StartsWith("CssProperty<", StringComparison.Ordinal) &&
                csharpType.EndsWith(">", StringComparison.Ordinal))
            {
                return $"{csharpType}.FromValue({initialValueExpr}, null)";
            }

            return null;
        }
    }
}
