using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using PeachPDF.SourceGenerators.Model;
using static PeachPDF.SourceGenerators.Emit.CodeToken;
using static PeachPDF.SourceGenerators.Emit.Identifier;

namespace PeachPDF.SourceGenerators.Emit
{
    /// <summary>
    /// Emits <c>CssPropertyRegistry.g.cs</c> (namespace <c>PeachPDF.Html.Core.Utils</c>, matching
    /// <c>CssUtils</c>) and <c>SvgPropertyRegistry.g.cs</c> (namespace <c>PeachPDF.Svg</c>, matching
    /// <c>SvgTreeBuilder</c>) from the parsed <c>css-properties.json</c> model. See CLAUDE.md's
    /// generator section and the css-properties.schema.json comments for the schema this reads.
    /// </summary>
    internal static class RegistryEmitter
    {
        public static string EmitHtmlRegistry(IReadOnlyList<PropertyEntry> entries)
        {
            var htmlEntries = entries.Where(e => e.Html is not null).ToList();
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generated by PeachPDF.SourceGenerators from css-properties.json. Do not edit by hand —");
            sb.AppendLine("// edit the JSON entry and rebuild. See CLAUDE.md's generator section.");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Frozen;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using PeachPDF.CSS;");
            sb.AppendLine("using PeachPDF.Html.Core.Dom;");
            sb.AppendLine("using PeachPDF.Html.Core.Entities;");
            sb.AppendLine("using PeachPDF.Html.Core.Parse;");
            sb.AppendLine();
            sb.AppendLine("namespace PeachPDF.Html.Core.Utils");
            sb.AppendLine("{");
            sb.AppendLine("    internal static partial class CssPropertyRegistry");
            sb.AppendLine("    {");

            foreach (var entry in htmlEntries)
                EmitHtmlEntryMethods(sb, entry);

            EmitHtmlSetterDictionary(sb, htmlEntries);
            EmitHtmlGetterDictionary(sb, htmlEntries);
            EmitHtmlValidatorDictionary(sb, htmlEntries);
            EmitHtmlSupportsValidatorDictionary(sb, htmlEntries);
            EmitInheritedProperties(sb, htmlEntries);
            EmitInitialValues(sb, htmlEntries);
            EmitSnapshotPropertyNames(sb, htmlEntries);
            EmitLogicalProperties(sb, htmlEntries);

            sb.AppendLine();
            sb.AppendLine("        internal static bool IsKnownProperty(string name) => _setters.ContainsKey(name);");
            sb.AppendLine();
            sb.AppendLine("        internal static bool IsInherited(string name) => InheritedProperties.Contains(name);");
            sb.AppendLine();
            sb.AppendLine("        internal static string? GetInitialValue(string name) => InitialValues.TryGetValue(name, out var v) ? v : null;");
            sb.AppendLine();
            sb.AppendLine("        internal static bool TrySet(CssValueParser parser, CssBox box, string name, string value) =>");
            sb.AppendLine("            _setters.TryGetValue(name, out var setter) && setter(parser, box, value);");
            sb.AppendLine();
            sb.AppendLine("        internal static string? Get(CssBox box, string name) =>");
            sb.AppendLine("            _getters.TryGetValue(name, out var getter) ? getter(box) : null;");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>Validation only — no box, no mutation, no side effects. The @supports render-layer oracle.</summary>");
            sb.AppendLine("        internal static bool SupportsDeclaration(CssValueParser parser, string name, string value) =>");
            sb.AppendLine("            _supportsValidators.TryGetValue(name, out var validator) && validator(parser, value);");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>Nominal-context overload for a caller (e.g. an @supports condition leaf) with no live parser/adapter of its own — grammar validation needs *an* adapter, not the document's real one.</summary>");
            sb.AppendLine("        internal static bool SupportsDeclaration(string name, string value) =>");
            sb.AppendLine("            SupportsDeclaration(new CssValueParser(new global::PeachPDF.Adapters.PdfSharpAdapter()), name, value);");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void EmitHtmlEntryMethods(StringBuilder sb, PropertyEntry entry)
        {
            var id = PascalCase(entry.Name);
            var html = entry.Html!;
            var isUnsupported = entry.CssDataTypes.Count == 1 && entry.CssDataTypes[0].Kind == DataTypeKind.Unsupported;

            sb.AppendLine();
            sb.AppendLine($"        // \"{entry.Name}\"");

            if (isUnsupported)
            {
                sb.AppendLine($"        private static bool Validate_{id}(CssValueParser parser, string value) => false;");
                sb.AppendLine($"        private static bool Supports_{id}(CssValueParser parser, string value) => false;");
                sb.AppendLine($"        private static bool Set_{id}(CssValueParser parser, CssBox box, string value) => false;");
                return;
            }

            var validatorExpr = html.CustomValidator is not null
                ? Substitute(html.CustomValidator, value: "value", parser: "parser")
                : ValidatorExpressionBuilder.BuildHtml(entry);

            sb.AppendLine($"        private static bool Validate_{id}(CssValueParser parser, string value) => {validatorExpr};");

            if (entry.SupportsCssDataTypes is not null)
            {
                var supportsExpr = ValidatorExpressionBuilder.BuildHtml(entry, entry.SupportsCssDataTypes,
                    entry.SupportsSupportedValues ?? entry.SupportedValues, entry.SupportsKeywordComparison ?? entry.KeywordComparison);
                sb.AppendLine($"        private static bool Supports_{id}(CssValueParser parser, string value) => {supportsExpr};");
            }
            else
            {
                sb.AppendLine($"        private static bool Supports_{id}(CssValueParser parser, string value) => Validate_{id}(parser, value);");
            }

            sb.AppendLine($"        private static bool Set_{id}(CssValueParser parser, CssBox box, string value)");
            sb.AppendLine("        {");
            sb.AppendLine($"            if (!Validate_{id}(parser, value)) return false;");
            sb.AppendLine($"            {BuildHtmlAssignment(entry)}");
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");

            if (html.HasGetter)
            {
                var getterExpr = html.GetterExpression is not null
                    ? Substitute(html.GetterExpression, box: "box")
                    : $"box.{html.PropertyPath}";
                sb.AppendLine($"        private static string? Get_{id}(CssBox box) => {getterExpr};");
            }
        }

        private static string BuildHtmlAssignment(PropertyEntry entry)
        {
            var html = entry.Html!;

            if (html.CustomSetter is not null)
                return Substitute(html.CustomSetter, value: "value", box: "box", parser: "parser");

            if (entry.CssDataTypes.Count == 1 && entry.CssDataTypes[0].Kind == DataTypeKind.EnumKeyword)
            {
                var dt = entry.CssDataTypes[0];
                return $"box.{html.PropertyPath} = CssProperty<{dt.EnumType}>.FromCssText(value, {dt.KeywordMap}, {dt.Fallback});";
            }

            if (entry.CssDataTypes.Count == 1 && entry.CssDataTypes[0].Kind == DataTypeKind.KeywordOrValue)
            {
                var dt = entry.CssDataTypes[0];
                var resolved = KeywordOrValueGrammar.Resolve(entry, dt);
                // A keyword-or-value property's html.valueComputation (e.g. word-spacing/letter-spacing's
                // "no-ems") must run on the raw authored text *before* FromCssText parses it - the box's
                // own generated property setter (StylePropertiesEmitter) no longer sees a string to run it
                // against once the property is typed, so this is the one place left with both the raw
                // string and a CssBox in scope. See StylePropertiesEmitter's doc comment.
                var rawValueExpr = html.ValueComputation switch
                {
                    null => "value",
                    "no-ems" => "box.NoEms(value)",
                    "font-size" => "box.ResolveFontSizeValueComputation(value)",
                    _ => throw new NotSupportedException(
                        $"\"{entry.Name}\" declares a keyword-or-value cssDataType with html.valueComputation " +
                        $"\"{html.ValueComputation}\", which RegistryEmitter does not implement."),
                };
                // Explicit type arguments: a method-group argument (int.TryParse) doesn't drive generic
                // inference for TValue the way a concrete delegate instance would.
                return $"box.{html.PropertyPath} = global::PeachPDF.CSS.CssKeywordOrValueParser.FromCssText<{dt.EnumType}, {resolved.CSharpType}>" +
                       $"({rawValueExpr}, {dt.KeywordMap}, {resolved.TryParseMethod}, {dt.Fallback});";
            }

            // A case-insensitively-matched keyword (plain "keyword", or the keyword side of a union like
            // "length" | "keyword") must be stored in its canonical (as-authored-in-JSON) casing, not the
            // raw input — every downstream layout/paint comparison against this field is an ordinal match
            // against a lowercase CssConstants.* literal, so an uncanonicalized "BLOCK" would validate but
            // then silently fail to match anything (issue #598). A non-keyword value (e.g. an actual length
            // for a union property) falls through the chain unchanged.
            var hasCaseInsensitiveKeyword = entry.KeywordComparison != KeywordComparison.Ordinal &&
                                             entry.CssDataTypes.Any(dt => dt.Kind == DataTypeKind.Keyword);
            if (hasCaseInsensitiveKeyword)
                return $"box.{html.PropertyPath} = {BuildKeywordCanonicalizationExpression(entry.SupportedValues, entry.KeywordComparison)};";

            return $"box.{html.PropertyPath} = value;";
        }

        /// <summary>Maps a case-insensitively-matched keyword back to its canonical spelling from
        /// <paramref name="supportedValues"/>; a value matching none of them (already validated as
        /// something else, e.g. a length) passes through unchanged.</summary>
        private static string BuildKeywordCanonicalizationExpression(IReadOnlyList<string>? supportedValues,
            KeywordComparison keywordComparison)
        {
            var values = supportedValues ?? Array.Empty<string>();
            if (values.Count == 0) return "value";

            var comparison = keywordComparison == KeywordComparison.OrdinalIgnoreCase
                ? "global::System.StringComparison.OrdinalIgnoreCase"
                : "global::System.StringComparison.InvariantCultureIgnoreCase";

            var chain = string.Concat(values.Select(v =>
                $"value.Equals({StringLiteral(v)}, {comparison}) ? {StringLiteral(v)} : "));
            return chain + "value";
        }

        private static void EmitHtmlSetterDictionary(StringBuilder sb, List<PropertyEntry> entries)
        {
            sb.AppendLine();
            sb.AppendLine("        private static readonly FrozenDictionary<string, Func<CssValueParser, CssBox, string, bool>> _setters =");
            sb.AppendLine("            new Dictionary<string, Func<CssValueParser, CssBox, string, bool>>(StringComparer.Ordinal)");
            sb.AppendLine("            {");
            foreach (var entry in entries)
                sb.AppendLine($"                [{StringLiteral(entry.Name)}] = Set_{PascalCase(entry.Name)},");
            sb.AppendLine("            }.ToFrozenDictionary(StringComparer.Ordinal);");
        }

        private static void EmitHtmlGetterDictionary(StringBuilder sb, List<PropertyEntry> entries)
        {
            sb.AppendLine();
            sb.AppendLine("        private static readonly FrozenDictionary<string, Func<CssBox, string?>> _getters =");
            sb.AppendLine("            new Dictionary<string, Func<CssBox, string?>>(StringComparer.Ordinal)");
            sb.AppendLine("            {");
            foreach (var entry in entries.Where(e => e.Html!.HasGetter))
                sb.AppendLine($"                [{StringLiteral(entry.Name)}] = Get_{PascalCase(entry.Name)},");
            sb.AppendLine("            }.ToFrozenDictionary(StringComparer.Ordinal);");
        }

        private static void EmitHtmlValidatorDictionary(StringBuilder sb, List<PropertyEntry> entries)
        {
            sb.AppendLine();
            sb.AppendLine("        private static readonly FrozenDictionary<string, Func<CssValueParser, string, bool>> _validators =");
            sb.AppendLine("            new Dictionary<string, Func<CssValueParser, string, bool>>(StringComparer.Ordinal)");
            sb.AppendLine("            {");
            foreach (var entry in entries)
                sb.AppendLine($"                [{StringLiteral(entry.Name)}] = Validate_{PascalCase(entry.Name)},");
            sb.AppendLine("            }.ToFrozenDictionary(StringComparer.Ordinal);");
        }

        private static void EmitHtmlSupportsValidatorDictionary(StringBuilder sb, List<PropertyEntry> entries)
        {
            sb.AppendLine();
            sb.AppendLine("        private static readonly FrozenDictionary<string, Func<CssValueParser, string, bool>> _supportsValidators =");
            sb.AppendLine("            new Dictionary<string, Func<CssValueParser, string, bool>>(StringComparer.Ordinal)");
            sb.AppendLine("            {");
            foreach (var entry in entries)
                sb.AppendLine($"                [{StringLiteral(entry.Name)}] = Supports_{PascalCase(entry.Name)},");
            sb.AppendLine("            }.ToFrozenDictionary(StringComparer.Ordinal);");
        }

        private static void EmitInheritedProperties(StringBuilder sb, List<PropertyEntry> entries)
        {
            sb.AppendLine();
            sb.AppendLine("        internal static readonly FrozenSet<string> InheritedProperties =");
            sb.AppendLine("            new HashSet<string>(StringComparer.OrdinalIgnoreCase)");
            sb.AppendLine("            {");
            foreach (var entry in entries.Where(e => e.Inherited))
                sb.AppendLine($"                {StringLiteral(entry.Name)},");
            sb.AppendLine("            }.ToFrozenSet(StringComparer.OrdinalIgnoreCase);");
        }

        private static void EmitInitialValues(StringBuilder sb, List<PropertyEntry> entries)
        {
            sb.AppendLine();
            sb.AppendLine("        internal static readonly FrozenDictionary<string, string?> InitialValues =");
            sb.AppendLine("            new Dictionary<string, string?>(StringComparer.OrdinalIgnoreCase)");
            sb.AppendLine("            {");
            foreach (var entry in entries.Where(e => e.InitialValueKind != InitialValueKind.None))
            {
                var valueExpr = entry.InitialValueKind == InitialValueKind.Literal
                    ? StringLiteral(entry.InitialValueText!)
                    : entry.InitialValueText; // Expression — spliced verbatim, e.g. CssConstants.DefaultFont
                sb.AppendLine($"                [{StringLiteral(entry.Name)}] = {valueExpr},");
            }
            sb.AppendLine("            }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);");
        }

        private static void EmitSnapshotPropertyNames(StringBuilder sb, List<PropertyEntry> entries)
        {
            sb.AppendLine();
            sb.AppendLine("        internal static readonly string[] SnapshotPropertyNames =");
            sb.AppendLine("        {");
            foreach (var entry in entries.Where(e => e.Html!.Snapshot))
                sb.AppendLine($"            {StringLiteral(entry.Name)},");
            sb.AppendLine("        };");
        }

        private static void EmitLogicalProperties(StringBuilder sb, List<PropertyEntry> entries)
        {
            sb.AppendLine();
            sb.AppendLine("        internal static readonly FrozenDictionary<string, (string Group, string Axis, string Side)> LogicalProperties =");
            sb.AppendLine("            new Dictionary<string, (string Group, string Axis, string Side)>(StringComparer.Ordinal)");
            sb.AppendLine("            {");
            foreach (var entry in entries.Where(e => e.Category == PropertyCategory.Logical))
            {
                var t = entry.ResolvesTo;
                var tuple = t is null ? "(\"\", \"\", \"\")" : $"({StringLiteral(t.Group)}, {StringLiteral(t.Axis)}, {StringLiteral(t.Side)})";
                sb.AppendLine($"                [{StringLiteral(entry.Name)}] = {tuple},");
            }
            sb.AppendLine("            }.ToFrozenDictionary(StringComparer.Ordinal);");
        }

        public static string EmitSvgRegistry(IReadOnlyList<PropertyEntry> entries)
        {
            var svgEntries = entries.Where(e => e.Svg is not null && e.Svg.ApplyIn == SvgApplyIn.Common).ToList();
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generated by PeachPDF.SourceGenerators from css-properties.json. Do not edit by hand —");
            sb.AppendLine("// edit the JSON entry and rebuild. See CLAUDE.md's generator section.");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Frozen;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using PeachPDF.Html.Adapters;");
            sb.AppendLine("using PeachPDF.Html.Adapters.Entities;");
            sb.AppendLine();
            sb.AppendLine("namespace PeachPDF.Svg");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>Everything a generated SVG customSetter/default setter needs beyond the raw value — see CLAUDE.md's generator section.</summary>");
            sb.AppendLine("    internal readonly struct SvgPropertyContext");
            sb.AppendLine("    {");
            sb.AppendLine("        public RAdapter Adapter { get; }");
            sb.AppendLine("        public RColor ContextColor { get; }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>The current viewport's diagonal (per the SVG percentage-length formula) — needed to resolve a percentage stroke-width/dashoffset/dasharray entry; null where no viewport is established yet.</summary>");
            sb.AppendLine("        public double? ViewportDiagonal { get; }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>Reclassifies a url()-referencing SvgPaint as a gradient vs. pattern reference against the current document's id registries — see SvgTreeBuilder.ResolveUrlPaintKind. The nominal @supports context uses the identity function.</summary>");
            sb.AppendLine("        public Func<SvgPaint, SvgPaint> ResolveUrlPaintKind { get; }");
            sb.AppendLine();
            sb.AppendLine("        public SvgPropertyContext(RAdapter adapter, RColor contextColor, double? viewportDiagonal, Func<SvgPaint, SvgPaint> resolveUrlPaintKind)");
            sb.AppendLine("        {");
            sb.AppendLine("            Adapter = adapter;");
            sb.AppendLine("            ContextColor = contextColor;");
            sb.AppendLine("            ViewportDiagonal = viewportDiagonal;");
            sb.AppendLine("            ResolveUrlPaintKind = resolveUrlPaintKind;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    internal static partial class SvgPropertyRegistry");
            sb.AppendLine("    {");

            foreach (var entry in svgEntries)
                EmitSvgEntryMethods(sb, entry);

            EmitSvgSetterDictionary(sb, svgEntries);
            EmitSvgValidatorDictionary(sb, svgEntries);
            EmitSvgInheritedProperties(sb, svgEntries);
            EmitSvgInitialValues(sb, svgEntries);

            sb.AppendLine();
            sb.AppendLine("        internal static bool IsKnownProperty(string name) => _setters.ContainsKey(name);");
            sb.AppendLine();
            sb.AppendLine("        internal static bool TrySet(SvgElement element, string name, string value, in SvgPropertyContext ctx) =>");
            sb.AppendLine("            _setters.TryGetValue(name, out var setter) && setter(element, ctx, value);");
            sb.AppendLine();
            sb.AppendLine("        internal static string? GetInitialValue(string name) => InitialValues.TryGetValue(name, out var v) ? v : null;");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>Validation only, with a nominal default context — the @supports render-layer oracle for SVG.</summary>");
            sb.AppendLine("        internal static bool SupportsDeclaration(string name, string value)");
            sb.AppendLine("        {");
            sb.AppendLine("            var ctx = new SvgPropertyContext(new global::PeachPDF.Adapters.PdfSharpAdapter(), RColor.Black, null, static p => p);");
            sb.AppendLine("            return _validators.TryGetValue(name, out var validator) && validator(ctx, value);");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void EmitSvgEntryMethods(StringBuilder sb, PropertyEntry entry)
        {
            var id = PascalCase(entry.Name);
            var svg = entry.Svg!;

            sb.AppendLine();
            sb.AppendLine($"        // \"{entry.Name}\"");

            var validatorExpr = svg.CustomValidator is not null
                ? Substitute(svg.CustomValidator, value: "value", ctx: "ctx")
                : ValidatorExpressionBuilder.BuildSvg(entry);

            sb.AppendLine($"        private static bool Validate_{id}(in SvgPropertyContext ctx, string value) => {validatorExpr};");

            sb.AppendLine($"        private static bool Set_{id}(SvgElement element, in SvgPropertyContext ctx, string value)");
            sb.AppendLine("        {");
            foreach (var line in BuildSvgSetterBody(entry, id).Split('\n'))
                sb.AppendLine($"            {line}");
            sb.AppendLine("        }");
        }

        private static string BuildSvgSetterBody(PropertyEntry entry, string id)
        {
            var svg = entry.Svg!;

            if (svg.CustomSetter is not null)
            {
                var custom = Substitute(svg.CustomSetter, value: "value", element: "element", ctx: "ctx");
                return $"if (!Validate_{id}(in ctx, value)) return false;\n{custom}\nreturn true;";
            }

            var kind = entry.CssDataTypes.Count == 1
                ? entry.CssDataTypes[0].Kind
                : throw new NotSupportedException($"\"{entry.Name}\" has no customSetter and its cssDataType is a union — a default SVG setter needs exactly one data type.");

            return kind switch
            {
                DataTypeKind.SvgPaint =>
                    "if (!global::PeachPDF.Svg.SvgValueParsers.TryParsePaint(value, ctx.Adapter, ctx.ContextColor, out var parsed)) return false;\n" +
                    $"element.{svg.PropertyPath} = ctx.ResolveUrlPaintKind(parsed);\nreturn true;",
                DataTypeKind.SvgOpacity =>
                    "if (!global::PeachPDF.Svg.SvgValueParsers.TryParseOpacity(value, out var parsed)) return false;\n" +
                    $"element.{svg.PropertyPath} = parsed;\nreturn true;",
                DataTypeKind.SvgLength =>
                    "var parsed = global::PeachPDF.Svg.SvgValueParsers.ParseLength(value, ctx.ViewportDiagonal);\n" +
                    $"if (parsed is null) return false;\nelement.{svg.PropertyPath} = parsed.Value;\nreturn true;",
                DataTypeKind.SvgLengthList =>
                    "var parsed = global::PeachPDF.Svg.SvgValueParsers.ParseDashArray(value, ctx.ViewportDiagonal);\n" +
                    $"if (parsed is null) return false;\nelement.{svg.PropertyPath} = parsed;\nreturn true;",
                DataTypeKind.CssOm => $"element.{svg.PropertyPath} = value;\nreturn true;",
                _ => throw new NotSupportedException(
                    $"DataTypeKind.{kind} has no default SVG setter and \"{entry.Name}\" declares no customSetter."),
            };
        }

        private static void EmitSvgSetterDictionary(StringBuilder sb, List<PropertyEntry> entries)
        {
            sb.AppendLine();
            sb.AppendLine("        private static readonly FrozenDictionary<string, Func<SvgElement, SvgPropertyContext, string, bool>> _setters =");
            sb.AppendLine("            new Dictionary<string, Func<SvgElement, SvgPropertyContext, string, bool>>(StringComparer.Ordinal)");
            sb.AppendLine("            {");
            foreach (var entry in entries)
                sb.AppendLine($"                [{StringLiteral(entry.Name)}] = (element, ctx, value) => Set_{PascalCase(entry.Name)}(element, in ctx, value),");
            sb.AppendLine("            }.ToFrozenDictionary(StringComparer.Ordinal);");
        }

        private static void EmitSvgValidatorDictionary(StringBuilder sb, List<PropertyEntry> entries)
        {
            sb.AppendLine();
            sb.AppendLine("        private static readonly FrozenDictionary<string, Func<SvgPropertyContext, string, bool>> _validators =");
            sb.AppendLine("            new Dictionary<string, Func<SvgPropertyContext, string, bool>>(StringComparer.Ordinal)");
            sb.AppendLine("            {");
            foreach (var entry in entries)
                sb.AppendLine($"                [{StringLiteral(entry.Name)}] = (ctx, value) => Validate_{PascalCase(entry.Name)}(in ctx, value),");
            sb.AppendLine("            }.ToFrozenDictionary(StringComparer.Ordinal);");
        }

        private static void EmitSvgInheritedProperties(StringBuilder sb, List<PropertyEntry> entries)
        {
            sb.AppendLine();
            sb.AppendLine("        internal static readonly FrozenSet<string> InheritedProperties =");
            sb.AppendLine("            new HashSet<string>(StringComparer.OrdinalIgnoreCase)");
            sb.AppendLine("            {");
            foreach (var entry in entries.Where(e => e.Inherited))
                sb.AppendLine($"                {StringLiteral(entry.Name)},");
            sb.AppendLine("            }.ToFrozenSet(StringComparer.OrdinalIgnoreCase);");
        }

        private static void EmitSvgInitialValues(StringBuilder sb, List<PropertyEntry> entries)
        {
            sb.AppendLine();
            sb.AppendLine("        internal static readonly FrozenDictionary<string, string?> InitialValues =");
            sb.AppendLine("            new Dictionary<string, string?>(StringComparer.OrdinalIgnoreCase)");
            sb.AppendLine("            {");
            foreach (var entry in entries.Where(e => e.InitialValueKind != InitialValueKind.None))
            {
                var valueExpr = entry.InitialValueKind == InitialValueKind.Literal
                    ? StringLiteral(entry.InitialValueText!)
                    : entry.InitialValueText;
                sb.AppendLine($"                [{StringLiteral(entry.Name)}] = {valueExpr},");
            }
            sb.AppendLine("            }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);");
        }
    }
}
