using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using PeachPDF.SourceGenerators.Model;

namespace PeachPDF.SourceGenerators.Emit
{
    /// <summary>
    /// Emits <c>CssBox.StyleProperties.g.cs</c> (namespace <c>PeachPDF.Html.Core.Dom</c>, <c>partial class
    /// CssBox</c>) — one cascaded property per JSON entry with an <c>html.area</c>/<c>propertyPath</c>.
    /// The property itself never parses <c>string</c> into a typed value: for an <c>enum-keyword</c>/
    /// <c>keyword-or-value</c> property, that parsing is the registry's job
    /// (<see cref="RegistryEmitter.BuildHtmlAssignment"/> calls <c>CssProperty&lt;T&gt;.FromCssText</c>/
    /// <c>CssKeywordOrValueParser.FromCssText</c> and assigns the *result* to the property), so the
    /// property's own get/set skeleton is the same shape for every <c>csharpDataType</c> - a plain field
    /// read/write through the area's copy-on-write plumbing (<see cref="ComputedStyleCow"/>), plus an
    /// optional invalidation call afterward (<c>html.invalidates</c>). The handful of properties whose
    /// *stored* value differs from what's handed to their setter declare <c>html.valueComputation</c>:
    /// <c>text-indent</c> ("text-indent", still a plain string-typed property) eagerly resolves a plain
    /// <c>em</c> length to points via this class's own hand-written <c>NoEmsTextIndent</c> helper, emitted
    /// by <see cref="EmitValueComputation"/> below. Every keyword-or-value-shaped property declaring
    /// <c>valueComputation</c> instead (<c>word-spacing</c>/<c>letter-spacing</c>'s "no-ems", <c>font-size
    /// </c>'s "font-size") is the one exception: that setter's parameter is already a parsed typed union
    /// by the time it runs - there is no raw string left for this class's own computation to act on, so
    /// <see cref="RegistryEmitter.BuildHtmlAssignment"/> runs the computation itself (via <c>box.NoEms</c>/
    /// <c>box.ResolveFontSizeValueComputation</c>) against the raw authored text, before parsing, and this
    /// emitter skips its own <c>EmitValueComputation</c> call entirely for that shape (see
    /// <see cref="EmitProperty"/>).
    /// </summary>
    internal static class StylePropertiesEmitter
    {
        public static string Emit(IReadOnlyList<PropertyEntry> entries)
        {
            // A legacy alias (page-break-after → break-after) declares the same html.area/propertyPath
            // as the property it aliases, so it shares that CssBox member rather than getting its own -
            // deduplicate by propertyPath, keeping the first entry's declaration (they're identical by
            // construction: RegistryEmitter dispatches both names' Set_X to the same box.PropertyPath).
            var properties = entries
                .Where(e => e.Html is { Area: not null, PropertyPath: not null })
                .GroupBy(e => e.Html!.PropertyPath)
                .Select(g => g.First())
                .ToList();

            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generated by PeachPDF.SourceGenerators from css-properties.json. Do not edit by hand —");
            sb.AppendLine("// edit the JSON entry and rebuild. See CLAUDE.md's generator section.");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using PeachPDF.Adapters;");
            sb.AppendLine("using PeachPDF.CSS;");
            sb.AppendLine("using PeachPDF.Html.Adapters.Entities;");
            sb.AppendLine("using PeachPDF.Html.Core.Entities;");
            sb.AppendLine("using PeachPDF.Html.Core.Parse;");
            sb.AppendLine("using PeachPDF.Html.Core.Utils;");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("namespace PeachPDF.Html.Core.Dom");
            sb.AppendLine("{");
            sb.AppendLine("    partial class CssBox");
            sb.AppendLine("    {");

            foreach (var entry in properties)
                EmitProperty(sb, entry);

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void EmitProperty(StringBuilder sb, PropertyEntry entry)
        {
            var html = entry.Html!;
            var areaField = AreaFieldName(html.Area!);
            var propertyPath = html.PropertyPath!;

            sb.AppendLine($"        public {html.CsharpDataType} {propertyPath}");
            sb.AppendLine("        {");
            sb.AppendLine($"            get => _computedStyle.{areaField}.{propertyPath};");
            sb.AppendLine("            set");
            sb.AppendLine("            {");

            var invalidates = html.Invalidates;
            if (invalidates is { Count: > 0 })
                sb.AppendLine("                var previousStyle = _computedStyle;");

            // A keyword-or-value property (e.g. word-spacing/letter-spacing) is already fully resolved -
            // its html.valueComputation ran in RegistryEmitter.BuildHtmlAssignment against the raw
            // authored string, before CssKeywordOrValueParser.FromCssText parsed it into the typed union
            // this setter actually receives, since a typed union has no string for this class's own
            // NoEms/NoEmsTextIndent helpers to run against. See RegistryEmitter's matching comment.
            var isKeywordOrValue = entry.CssDataTypes.Count == 1 && entry.CssDataTypes[0].Kind == DataTypeKind.KeywordOrValue;

            var valueExpr = "value";
            if (html.ValueComputation is not null && !isKeywordOrValue)
            {
                valueExpr = "resolved";
                EmitValueComputation(sb, html.ValueComputation, entry);
            }

            sb.AppendLine($"                var area = _computedStyle.{areaField};");
            sb.AppendLine($"                var newArea = area.SetPropertyValue(area.{propertyPath}, {valueExpr}, static (a, v) => a with {{ {propertyPath} = v }});");
            sb.AppendLine($"                _computedStyle = _computedStyle.AdoptArea(area, newArea, static (s, a) => s with {{ {areaField} = a }});");

            if (invalidates is { Count: > 0 })
            {
                foreach (var method in invalidates)
                    sb.AppendLine($"                if (!ReferenceEquals(_computedStyle, previousStyle)) DerivedStyle.{method}();");
            }

            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        /// <summary>Strips the trailing <c>"Area"</c> from an <c>html.area</c> value to get
        /// <see cref="ComputedStyle"/>'s field name for it (<c>"BoxModelArea"</c> → <c>"BoxModel"</c>) -
        /// the convention every one of the 16 area records follows.</summary>
        private static string AreaFieldName(string area) =>
            area.EndsWith("Area", StringComparison.Ordinal) ? area.Substring(0, area.Length - "Area".Length) : area;

        private static void EmitValueComputation(StringBuilder sb, string valueComputation, PropertyEntry entry)
        {
            switch (valueComputation)
            {
                case "no-ems":
                    sb.AppendLine("                var resolved = NoEms(value);");
                    break;
                case "text-indent":
                    sb.AppendLine("                var resolved = NoEmsTextIndent(value);");
                    break;
                default:
                    throw new NotSupportedException(
                        $"\"{entry.Name}\" declares html.valueComputation \"{valueComputation}\", which StylePropertiesEmitter does not implement.");
            }
        }
    }
}
