using System.Collections.Generic;
using System.Linq;
using System.Text;
using PeachPDF.SourceGenerators.Model;

namespace PeachPDF.SourceGenerators.Emit
{
    /// <summary>
    /// Emits <c>CssBox.StyleProperties.g.cs</c> (namespace <c>PeachPDF.Html.Core.Dom</c>, <c>partial class
    /// CssBox</c>) — one cascaded property per JSON entry with an <c>html.area</c>/<c>propertyPath</c>.
    /// The property itself never parses <c>string</c> into a typed value: for an <c>enum-keyword</c>/
    /// <c>keyword-or-value</c> property, that parsing is the registry's job
    /// (<see cref="RegistryEmitter.BuildHtmlAssignment"/> calls <c>CssProperty&lt;T&gt;.FromCssText</c>/
    /// <c>CssKeywordOrValueParser.FromCssText</c> and assigns the *result* to the property), so the
    /// property's own get/set skeleton is the same shape for every <c>csharpDataType</c> - a plain field
    /// read/write through the area's copy-on-write plumbing (<see cref="ComputedStyleCow"/>), plus an
    /// optional invalidation call afterward (<c>html.invalidates</c>). The handful of properties whose
    /// *stored* value differs from what's handed to their setter declare <c>html.valueComputation</c>:
    /// <c>font-size</c> ("font-size", see <see cref="EmitFontSizeValueComputation"/>) eagerly resolves a
    /// parent-relative length to points; <c>word-spacing</c>/<c>letter-spacing</c> ("no-ems") and
    /// <c>text-indent</c> ("text-indent") eagerly resolve a plain <c>em</c> length the same way, via the
    /// hand-written <c>NoEms</c>/<c>NoEmsTextIndent</c> helpers this class still keeps on <c>CssBox</c>.
    /// </summary>
    internal static class StylePropertiesEmitter
    {
        public static string Emit(IReadOnlyList<PropertyEntry> entries)
        {
            // A legacy alias (page-break-after → break-after) declares the same html.area/propertyPath
            // as the property it aliases, so it shares that CssBox member rather than getting its own -
            // deduplicate by propertyPath, keeping the first entry's declaration (they're identical by
            // construction: RegistryEmitter dispatches both names' Set_X to the same box.PropertyPath).
            var properties = entries
                .Where(e => e.Html is { Area: not null, PropertyPath: not null })
                .GroupBy(e => e.Html!.PropertyPath)
                .Select(g => g.First())
                .ToList();

            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generated by PeachPDF.SourceGenerators from css-properties.json. Do not edit by hand —");
            sb.AppendLine("// edit the JSON entry and rebuild. See CLAUDE.md's generator section.");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using PeachPDF.Adapters;");
            sb.AppendLine("using PeachPDF.CSS;");
            sb.AppendLine("using PeachPDF.Html.Adapters.Entities;");
            sb.AppendLine("using PeachPDF.Html.Core.Entities;");
            sb.AppendLine("using PeachPDF.Html.Core.Parse;");
            sb.AppendLine("using PeachPDF.Html.Core.Utils;");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("namespace PeachPDF.Html.Core.Dom");
            sb.AppendLine("{");
            sb.AppendLine("    partial class CssBox");
            sb.AppendLine("    {");

            foreach (var entry in properties)
                EmitProperty(sb, entry);

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void EmitProperty(StringBuilder sb, PropertyEntry entry)
        {
            var html = entry.Html!;
            var areaField = AreaFieldName(html.Area!);
            var propertyPath = html.PropertyPath!;

            sb.AppendLine($"        public {html.CsharpDataType} {propertyPath}");
            sb.AppendLine("        {");
            sb.AppendLine($"            get => _computedStyle.{areaField}.{propertyPath};");
            sb.AppendLine("            set");
            sb.AppendLine("            {");

            var invalidates = html.Invalidates;
            if (invalidates is { Count: > 0 })
                sb.AppendLine("                var previousStyle = _computedStyle;");

            var valueExpr = "value";
            if (html.ValueComputation is not null)
            {
                valueExpr = "resolved";
                EmitValueComputation(sb, html.ValueComputation, entry);
            }

            sb.AppendLine($"                var area = _computedStyle.{areaField};");
            sb.AppendLine($"                var newArea = area.SetPropertyValue(area.{propertyPath}, {valueExpr}, static (a, v) => a with {{ {propertyPath} = v }});");
            sb.AppendLine($"                _computedStyle = _computedStyle.AdoptArea(area, newArea, static (s, a) => s with {{ {areaField} = a }});");

            if (invalidates is { Count: > 0 })
            {
                foreach (var method in invalidates)
                    sb.AppendLine($"                if (!ReferenceEquals(_computedStyle, previousStyle)) DerivedStyle.{method}();");
            }

            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        /// <summary>Strips the trailing <c>"Area"</c> from an <c>html.area</c> value to get
        /// <see cref="ComputedStyle"/>'s field name for it (<c>"BoxModelArea"</c> → <c>"BoxModel"</c>) -
        /// the convention every one of the 16 area records follows.</summary>
        private static string AreaFieldName(string area) =>
            area.EndsWith("Area", System.StringComparison.Ordinal) ? area.Substring(0, area.Length - "Area".Length) : area;

        private static void EmitValueComputation(StringBuilder sb, string valueComputation, PropertyEntry entry)
        {
            switch (valueComputation)
            {
                case "font-size":
                    EmitFontSizeValueComputation(sb);
                    break;
                case "no-ems":
                    sb.AppendLine("                var resolved = NoEms(value);");
                    break;
                case "text-indent":
                    sb.AppendLine("                var resolved = NoEmsTextIndent(value);");
                    break;
                default:
                    throw new System.NotSupportedException(
                        $"\"{entry.Name}\" declares html.valueComputation \"{valueComputation}\", which StylePropertiesEmitter does not implement.");
            }
        }

        /// <summary>
        /// <c>font-size</c>'s eager em/ex/percent/smaller/larger-to-absolute-points resolution - fixed,
        /// generator-owned C#, not derived from JSON data (there is exactly one property that needs this
        /// shape today). <c>calc()</c> and <c>rem</c> stay lazy, resolved later by
        /// <see cref="DerivedStyle.ActualFont"/>: <c>calc()</c> needs real layout-time container-query
        /// information not available at cascade time, and <c>rem</c> resolves against a single, non-chained
        /// reference so it can't compound across generations regardless of when it resolves. Every other
        /// parent-relative form needs eager conversion here because <c>InheritStyle</c> adopts the whole
        /// <c>Font</c> area from parent to child *by reference* - see the hand-written property this
        /// mirrors (<c>CssBox.StyleProperties.cs</c>'s <c>FontSize</c>, before the storage-generator PR)
        /// for the full reasoning.
        /// </summary>
        private static void EmitFontSizeValueComputation(StringBuilder sb)
        {
            sb.AppendLine("                string resolved;");
            sb.AppendLine("                var trimmed = value.Trim();");
            sb.AppendLine("                if (!CssValueParser.IsCalcFunction(value) && ParentBox is { } parent &&");
            sb.AppendLine("                    (CssValueParser.GetCssTokens(value) is [UnitToken unitToken] &&");
            sb.AppendLine("                        Length.GetUnit(unitToken.Unit) is Length.Unit.Em or Length.Unit.Ex or Length.Unit.Percent");
            sb.AppendLine("                     || trimmed.Equals(CssConstants.Smaller, StringComparison.OrdinalIgnoreCase)");
            sb.AppendLine("                     || trimmed.Equals(CssConstants.Larger, StringComparison.OrdinalIgnoreCase)))");
            sb.AppendLine("                {");
            sb.AppendLine("                    var pixelsPerPoint = (HtmlContainer?.Adapter as PdfSharpAdapter)?.PixelsPerPoint ?? 1.0;");
            sb.AppendLine("                    var parentSizePt = parent.ActualFont.Size * pixelsPerPoint;");
            sb.AppendLine();
            sb.AppendLine("                    var points = FontSizeResolver.Resolve(trimmed, parentSizePt, parentSizePt);");
            sb.AppendLine("                    resolved = $\"{points.ToString(System.Globalization.NumberFormatInfo.InvariantInfo)}pt\";");
            sb.AppendLine("                }");
            sb.AppendLine("                else");
            sb.AppendLine("                {");
            sb.AppendLine("                    resolved = value;");
            sb.AppendLine("                }");
            sb.AppendLine();
        }
    }
}
