#!/usr/bin/env python3
"""Generates src/PeachPDF/Text/EmojiProperties.Data.g.cs from the Unicode Character Database's
emoji-variation-sequences.txt and emoji-data.txt (Unicode 18.0.0, UTS #51 - see
https://www.unicode.org/reports/tr51/), matching the version already checked in for Scripts.txt.

Two sorted, non-overlapping range tables:

* VariationBases - every code point that is the base of an entry in emoji-variation-sequences.txt.
  These are exactly CSS Fonts 4's "Emoji Presentation Participating Code Points": the only characters
  font-variant-emoji affects.
* EmojiPresentationRanges - every code point with the Emoji_Presentation property (emoji-data.txt), which
  is what font-variant-emoji: unicode uses to tell an emoji-default character from a text-default one.

Plain generated C# rather than the Brotli-resource shape of generate_script_table.py: a few hundred
ranges do not justify a resource, and a source table works where Brotli is unavailable (WebAssembly).

Re-run whenever the two .txt files are refreshed to a newer Unicode version. No third-party packages.
"""
import os
import re

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_PATH = os.path.normpath(os.path.join(
    SCRIPT_DIR, "..", "..", "src", "PeachPDF", "Text", "EmojiProperties.Data.g.cs"))

VARIATION_LINE_RE = re.compile(r'^([0-9A-Fa-f]{4,6})\s+(FE0E|FE0F)\s*;')
PROPERTY_LINE_RE = re.compile(r'^([0-9A-Fa-f]{4,6})(?:\.\.([0-9A-Fa-f]{4,6}))?\s*;\s*(\w+)')


def coalesce(codepoints):
    runs = []
    for cp in sorted(set(codepoints)):
        if runs and runs[-1][1] + 1 == cp:
            runs[-1][1] = cp
        else:
            runs.append([cp, cp])
    return runs


def read_variation_bases():
    bases = []
    with open(os.path.join(SCRIPT_DIR, "emoji-variation-sequences.txt"), encoding="utf-8") as f:
        for line in f:
            m = VARIATION_LINE_RE.match(line)
            if m:
                bases.append(int(m.group(1), 16))
    return coalesce(bases)


def read_property(name):
    cps = []
    with open(os.path.join(SCRIPT_DIR, "emoji-data.txt"), encoding="utf-8") as f:
        for line in f:
            if line.startswith("#"):
                continue
            m = PROPERTY_LINE_RE.match(line)
            if m and m.group(3) == name:
                start = int(m.group(1), 16)
                end = int(m.group(2), 16) if m.group(2) else start
                cps.extend(range(start, end + 1))
    return coalesce(cps)


def emit(name, runs):
    rows = []
    for i in range(0, len(runs), 4):
        rows.append("            " + " ".join("(0x%X, 0x%X)," % (a, b) for a, b in runs[i:i + 4]))
    return "        private static readonly (int Start, int End)[] %s =\n        [\n%s\n        ];\n" % (
        name, "\n".join(rows))


def main():
    variation = read_variation_bases()
    presentation = read_property("Emoji_Presentation")
    out = (
        "// <auto-generated>\n"
        "// Generated by assets/unicode/generate_emoji_table.py from Unicode 18.0.0's\n"
        "// emoji-variation-sequences.txt and emoji-data.txt. Do not edit by hand; re-run the script.\n"
        "// </auto-generated>\n"
        "\n"
        "namespace PeachPDF.Text\n"
        "{\n"
        "    internal static partial class EmojiProperties\n"
        "    {\n"
        + emit("VariationBases", variation) + "\n"
        + emit("EmojiPresentationRanges", presentation) +
        "    }\n"
        "}\n")
    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write(out)
    print("VariationBases: %d ranges; EmojiPresentation: %d ranges" % (len(variation), len(presentation)))


if __name__ == "__main__":
    main()
